version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenvol:/var/jenkins_home
volumes:
  jenvol:
    external: true
