FROM ubuntu:latest

######ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y \
&& apt install -y iproute2 \
########&& apt install x11-common \
&& apt install x11-apps -y

#RUN apt update && apt install -y iproute2 && apt install x11-common && apt install x11-apps

RUN rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]