#!/bin/bash

#setup working environment
PARENT_DIR=`dirname "$PWD"`

#setup souri=cung files
CONFIG_FILE=${PARENT_DIR}/bin/config.sh
FUNCTION_FILE=${PARENT_DIR}/bin/dfunction.sh

if [ "${IS_CONFIG}" != "YES" ]; then
   echo "run source..."
   source ${CONFIG_FILE}
fi

source ${FUNCTION_FILE}

clear

dcmd="docker container stop  ${CON_DEBIAN_NAME}"

echo "This is the docker command."
echo "To stop running containers  ${CON_DEBIAN_NAME}..."
echo ""
echo "$dcmd"
echo ""

if [ "$PROMPT_MODE" == "Yes" ]; then
    read -p "Enter the docker command as shown...: " user_input
    runcmd
else
    echo "Prompt Mode Disabled, Running The Docker Command..."
    $dcmd

fi

